"""Implementation of ``ai-sdlc init``."""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any

import yaml

from .constants import (
    AGENT_CHOICES,
    DEFAULT_ADOPTION_SCOPE,
    DEFAULT_SELECTED_PACKS,
    EXPECTED_DIRECTORIES,
    HARNESS_VERSION,
    MANAGED_FILE_PATHS,
    TEMPLATE_VERSION,
)
from .context import _DEFAULT_BUDGET_CONFIGURATION
from .detect import detect_project_signals
from .files import resolve_under_root, write_text
from .manifest import build_managed_file_record, update_managed_file_records, write_manifest


def _timestamp() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _adapter_config(agent: str) -> dict[str, str]:
    return {
        "codex": "requested-deferred" if agent in {"codex", "both"} else "not-installed",
        "claude_code": "requested-deferred" if agent in {"claude-code", "both"} else "not-installed",
        "gemini_cli": "requested-deferred" if agent == "gemini-cli" else "not-installed",
    }


def build_config(root: Path, agent: str) -> dict[str, Any]:
    signals = detect_project_signals(root)
    return {
        "harness_version": HARNESS_VERSION,
        "template_version": TEMPLATE_VERSION,
        "adoption_scope": DEFAULT_ADOPTION_SCOPE,
        "selected_packs": list(DEFAULT_SELECTED_PACKS),
        "context_budget": asdict(_DEFAULT_BUDGET_CONFIGURATION),
        "adapters": _adapter_config(agent),
        "project": {
            "git_repo": signals["git_repo"],
            "detected_languages": signals["detected_languages"],
            "detected_package_managers": signals["detected_package_managers"],
            "detected_test_frameworks": signals["detected_test_frameworks"],
            "detected_ci": signals["detected_ci"],
            "existing_agent_files": signals["existing_agent_files"],
        },
    }


def build_state(root: Path) -> dict[str, Any]:
    return {
        "cache_only": True,
        "last_init_at": _timestamp(),
        "detected_signals": detect_project_signals(root),
    }


def build_selected_packs() -> dict[str, Any]:
    return {
        "selected_packs": [
            {"id": pack_id, "version": TEMPLATE_VERSION, "enabled": True} for pack_id in DEFAULT_SELECTED_PACKS
        ]
    }


def build_agent_instructions() -> str:
    return """# AI SDLC Harness Agent Instructions

Generated by AI SDLC Harness. Do not edit this file directly.

This repository has an AI SDLC Harness scaffold installed.

Controlled `.harness/` files are read-only for coding agents unless the human explicitly asks for harness maintenance:

- `.harness/config.yaml`
- `.harness/state.json`
- `.harness/manifest.json`
- `.harness/generated/agent-instructions.md`
- `.harness/packs/selected.yaml`

Current generated instructions provide bootstrap guidance only. They do not compile task-specific context or install agent adapters.

Use this file only as a bootstrap notice. Human instructions and future generated task artifacts remain the source of task-specific intent.
"""


def _managed_contents(root: Path, agent: str) -> dict[PurePosixPath, str]:
    return {
        PurePosixPath(".harness/config.yaml"): yaml.safe_dump(build_config(root, agent), sort_keys=False),
        PurePosixPath(".harness/state.json"): json.dumps(build_state(root), indent=2, sort_keys=True) + "\n",
        PurePosixPath(".harness/generated/agent-instructions.md"): build_agent_instructions(),
        PurePosixPath(".harness/packs/selected.yaml"): yaml.safe_dump(build_selected_packs(), sort_keys=False),
    }


def init_project(root: Path, *, agent: str = "none", dry_run: bool = False, force: bool = False) -> tuple[int, list[str]]:
    if agent not in AGENT_CHOICES:
        return 2, [f"Unsupported agent value: {agent}"]

    messages: list[str] = []
    contents = _managed_contents(root, agent)
    created_managed_paths: list[PurePosixPath] = []

    for directory in EXPECTED_DIRECTORIES:
        target = resolve_under_root(root, directory)
        if target.exists():
            messages.append(f"skip existing directory {directory.as_posix()}")
        else:
            messages.append(f"{'would create' if dry_run else 'create'} directory {directory.as_posix()}")
            if not dry_run:
                target.mkdir(parents=True, exist_ok=True)

    known_managed = {path.as_posix() for path in MANAGED_FILE_PATHS}
    for managed_path, content in contents.items():
        if managed_path.as_posix() not in known_managed:
            return 2, [f"Refusing unknown managed path: {managed_path.as_posix()}"]
        target = resolve_under_root(root, managed_path)
        existed = target.exists()
        if existed and not force:
            messages.append(f"skip existing file {managed_path.as_posix()}")
            continue
        action = "would rewrite" if existed and force and dry_run else None
        action = action or ("rewrite" if existed and force else None)
        action = action or ("would create" if dry_run else "create")
        messages.append(f"{action} file {managed_path.as_posix()}")
        if not dry_run:
            write_text(target, content)
            if not existed:
                created_managed_paths.append(managed_path)

    manifest_path = PurePosixPath(".harness/manifest.json")
    manifest_target = resolve_under_root(root, manifest_path)
    if dry_run:
        messages.append("would create manifest .harness/manifest.json" if not manifest_target.exists() else "would refresh manifest .harness/manifest.json")
    elif manifest_target.exists() and not force:
        if not created_managed_paths:
            messages.append("skip existing manifest .harness/manifest.json")
        else:
            update_managed_file_records(
                root,
                [build_managed_file_record(root, path) for path in created_managed_paths],
            )
            messages.append("refreshed manifest .harness/manifest.json")
    else:
        write_manifest(root, upgrade_to_v2=force)
        messages.append("refreshed manifest .harness/manifest.json")

    if agent != "none":
        messages.append("adapter installation is not performed by init; request recorded in config")
    messages.append("root AGENTS.md, CLAUDE.md, and GEMINI.md were not modified")
    return 0, messages
